# Basic Information
title: Bolun Zhang's Personal Site
author: Bolun Zhang
github_username: coolsteed

defaults:
  -
    scope:
      path: "posts" # 空字符串所有的文件。这里指posts文件夹
    values:
      layout: "default"
      theme: minimal
      permalink: date  # 这是指博客文章的网址格式


# Build Setting
theme: minimal
exclude:
  - Gemfile
  - Gemfile.lock